language: bash

install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

before_script:
  # Create conda virtual environments
  - conda env create -f envs/main.yml
  - conda env create -f envs/dev.yml
  # Activate the main env
  - conda activate binding-scanner && echo $CONDA_DEFAULT_ENV

script:
  - echo 123
  # Download the ATtRACT db
  - bash scripts/download-ATtRACT-motifs.sh -o ATtRACT
  - ls -al
  - ls -al ATtRACT
  # Extract motifs for hsa
  #- mkdir ATtRACT_hsa
  #- python scripts/format-ATtRACT-motifs.py \
  #  --pwms tests/unit/format-ATtRACT-motifs/ATtRACT/pwm.txt \
  #  --names tests/unit/format-ATtRACT-motifs/ATtRACT/ATtRACT_db.txt \
  #  --organism hsa \
  #  --outdir ATtRACT_hsa
  - # check md5

  # mmu

