language: bash

install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

before_script:
  # Create conda virtual environments
  - conda env create -f envs/main.yml
  - conda env create -f envs/dev.yml
  - conda env create -f envs/plot_heatmap_of_MotEvo_results.yml
  - conda env create -f envs/motevo.yml
  - conda env create -f envs/combine-motevo-results.yml
  # Activate the main env
  - conda activate binding-scanner && echo $CONDA_DEFAULT_ENV

script:
  # Download and extract the ATtRACT db
  #- bash scripts/download-ATtRACT-motifs.sh -o ATtRACT # this curl/wget do not work on Travis machine...
  # Extract the backup db
  - mkdir ATtRACT_backup_05072020
  - unzip resources/ATtRACT_backup_05072020.zip -d ATtRACT_backup_05072020
  # Extract motifs for Homo sapiens
  - mkdir tests/unit/format-ATtRACT-motifs/ATtRACT_hsa
  - conda activate motevo
  - >
    python scripts/format-ATtRACT-motifs.py
    --pwms tests/unit/format-ATtRACT-motifs/ATtRACT/pwm.txt
    --names tests/unit/format-ATtRACT-motifs/ATtRACT/ATtRACT_db.txt
    --organism Homo_sapiens
    --outdir tests/unit/format-ATtRACT-motifs/ATtRACT_hsa
  - md5sum --check tests/unit/format-ATtRACT-motifs/expected_output_hsa.md5
  # Extract motifs for Mus musculus
  - mkdir tests/unit/format-ATtRACT-motifs/ATtRACT_mmu
  - >
    python scripts/format-ATtRACT-motifs.py
    --pwms tests/unit/format-ATtRACT-motifs/ATtRACT/pwm.txt
    --names tests/unit/format-ATtRACT-motifs/ATtRACT/ATtRACT_db.txt
    --organism Mus_musculus
    --outdir tests/unit/format-ATtRACT-motifs/ATtRACT_mmu
  - md5sum --check tests/unit/format-ATtRACT-motifs/expected_output_mmu.md5
  # Test combine-motevo-results.py script
  - conda activate combine-motevo-results
  - >
    python workflow/scripts/combine-motevo-results.py
    --input_directories tests/unit/combine_results/motif_HNRNPF_820 tests/unit/combine_results/motif_HNRNPF_821 tests/unit/combine_results/motif_HNRNPF_822 tests/unit/combine_results/motif_HNRNPF_823 tests/unit/combine_results/motif_HNRNPF_824
    --filename posterior_sites
    --outfile tests/unit/combine_results/combined_MotEvo_results.tsv
  - md5sum --check tests/unit/combine_results/expected_output.md5
  # Test heatmap.r script script
  - conda activate plot_heatmap_of_MotEvo_results
  - >
    Rscript workflow/scripts/heatmap.r 
    --input_tsv tests/unit/Plot-heatmap-for-motifs/combined_MotEvo_results.tsv 
    --input_sequence ATGTGAGTGAAGTGTGGGAAAGATGACTCGATATATCTGGATGCTAGGGATCGGATGGCGATACG
    --outfile tests/unit/Plot-heatmap-for-motifs/ProbabilityvsSequences.pdf
  - md5sum --check tests/unit/Plot-heatmap-for-motifs/expected_output.md5
  - conda activate binding-scanner
  # Test snakemake Rulegraph and DAG
  - bash tests/integration/execution/snakemake_rulegraph_run.sh
  - bash tests/integration/execution/snakemake_dag_run.sh
  # Test pipeline execution: local, conda envs:
  - bash tests/integration/execution/snakemake_local_run_conda_environments.sh
  - md5sum --check tests/integration/expected_output.md5
  
